server:
  port: 8082
  
spring:
  application:
    name: order-service
    
  datasource:
    url: jdbc:postgresql://order-postgres:5432/order_service
    username: postgres
    password: postgres
    
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      retries: 3
      acks: all
      batch-size: 16384
      properties:
        retry.backoff.ms: 1000
        request.timeout.ms: 30000
        max.block.ms: 60000
    
eureka:
  client:
    enabled: false
    
notification:
  kafka:
    topic: notification-events
    
logging:
  level:
    com.ecommerce.order: DEBUG
    org.springframework.kafka: INFO 