server:
  port: 8083
  
spring:
  application:
    name: order-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    
  kafka:
    bootstrap-servers: localhost:9092
    
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
notification:
  kafka:
    topic: notification-events
    
logging:
  level:
    com.ecommerce.order: DEBUG
    org.springframework.kafka: INFO 