version: '3.8'

services:
  # MongoDB for notification service
  mongodb:
    image: mongo:7.0
    container_name: notification-mongodb
    ports:
      - "27017:27017"
    volumes:
      - notification_mongodb_data:/data/db
    networks:
      - notification-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: notification-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - notification-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: notification-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - notification-network

  # Kafka UI for monitoring Kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: notification-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: notification-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - notification-network

  # Notification service
  notification-service:
    build:
      context: ../backend/services/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - mongodb
      - kafka
    ports:
      - "8085:8085"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/notification-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EUREKA_CLIENT_ENABLED: 'false'
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge

volumes:
  notification_mongodb_data: 