server:
  port: 8085
  
spring:
  application:
    name: notification-service
    
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification-service
      
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
notification:
  kafka:
    topic: notification-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true 