server:
  port: 8085
  
spring:
  application:
    name: notification-service
    
  data:
    mongodb:
      uri: mongodb://mongodb:27017/notification-service
      
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      
eureka:
  client:
    enabled: false
    
notification:
  kafka:
    topic: notification-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.ecommerce.notification: DEBUG
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: DEBUG 